# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from AnimCanvas import AnimationWidget


# Класс определяющий верстку интерфейса главного окна приложения
# Собран в QtDesigner и сохранен в interface.ui
# Затем interface.ui переведен в Python-файл следующими консольными командами:
# # cd path/to/project
# # pyuic6 interface.ui -o interface.py
# После чего доработан руками
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 472)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1011, 471))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(2, 2, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")

        self.hunters_lbl = QtWidgets.QLabel(self.groupBox)
        self.hunters_lbl.setGeometry(QtCore.QRect(35, 0, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(12)
        self.hunters_lbl.setFont(font)
        self.hunters_lbl.setObjectName("hunters_lbl")

        self.victims_lbl = QtWidgets.QLabel(self.groupBox)
        self.victims_lbl.setGeometry(QtCore.QRect(0, 35, 16, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(12)
        self.victims_lbl.setFont(font)
        self.victims_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.victims_lbl.setWordWrap(True)
        self.victims_lbl.setObjectName("victims_lbl")

        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(19, 19, 322, 409))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 461, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)

        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)

        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.groupBox)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.addHunterBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addHunterBtn.setFont(font)
        self.addHunterBtn.setObjectName("addHunterBtn")
        self.horizontalLayout_2.addWidget(self.addHunterBtn)

        self.addVictimBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addVictimBtn.setFont(font)
        self.addVictimBtn.setObjectName("addVictimBtn")
        self.horizontalLayout_2.addWidget(self.addVictimBtn)

        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.canvas = AnimationWidget()
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hunters_lbl.setText(_translate("MainWindow", "О х о т н и к и"))
        self.victims_lbl.setText(_translate("MainWindow", "Ж е р т в ы"))
        self.addHunterBtn.setText(_translate("MainWindow", "Добавить охотника"))
        self.addVictimBtn.setText(_translate("MainWindow", "Добавить жертву"))


# Класс диалогового (модального) окна для создания объектов (полностью написан руками)
class CustomDialog(QtWidgets.QDialog):
    def __init__(self, type):
        super().__init__()

        if type == 'victim':
            self.setWindowTitle('Добавить жертву')
        else:
            self.setWindowTitle('Добавить охотника')

        # Создаем кнопки нашего окна
        dialog_buttons = QtWidgets.QDialogButtonBox.StandardButton.Ok | QtWidgets.QDialogButtonBox.StandardButton.Cancel

        self.buttonBox = QtWidgets.QDialogButtonBox(dialog_buttons)
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).setText('Ок')
        self.buttonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Cancel).setText('Отмена')
        self.buttonBox.accepted.connect(self.custom_accept)
        self.buttonBox.rejected.connect(self.custom_reject)

        # Вадидатор на регулярке на введение только вещественных чисел
        float_validator = QtGui.QRegularExpressionValidator(QtCore.QRegularExpression(r'[+-]?([0-9]*[.])?[0-9]+'))

        # victim = Victim(plt, self.canvas.ax, start_x=0, start_y=0, direction=30, speed=0.3, max_angle_of_rotation=45,
        #                 angle_of_vision=30, len_of_vision=10)
        # hunter =Hunter(plt, self.canvas.ax, start_x=-4, start_y=2, direction=-10, speed=0.5, max_angle_of_rotation=10,
        #                  angle_of_vision=30, len_of_vision=10)

        # Создаем поля ввода и вешаем на них валидатор
        font = QtGui.QFont()
        font.setBold(True)
        self.start_point_msg = QtWidgets.QLabel("Начальное положение (декартова система)")
        self.start_point_msg.setFont(font)
        self.start_x_le = QtWidgets.QLineEdit(self)
        self.start_x_le.setValidator(float_validator)
        self.start_y_le = QtWidgets.QLineEdit(self)
        self.start_y_le.setValidator(float_validator)

        self.vector_msg = QtWidgets.QLabel("Скорость и направление (полярная система)")
        self.vector_msg.setFont(font)
        self.speed_le = QtWidgets.QLineEdit(self)
        self.speed_le.setValidator(float_validator)
        self.direction_le = QtWidgets.QLineEdit(self)
        self.direction_le.setValidator(float_validator)

        self.rotation_msg = QtWidgets.QLabel("Максимальный угол поворота")
        self.rotation_msg.setFont(font)
        self.max_angle_of_rotation_le = QtWidgets.QLineEdit(self)
        self.max_angle_of_rotation_le.setValidator(float_validator)

        self.vision_msg = QtWidgets.QLabel("Конус визирования (полярная система)")
        self.vision_msg.setFont(font)
        self.angle_of_vision_le = QtWidgets.QLineEdit(self)
        self.angle_of_vision_le.setValidator(float_validator)
        self.len_of_vision_le = QtWidgets.QLineEdit(self)
        self.len_of_vision_le.setValidator(float_validator)

        # Собираем наше окно из созданных фрагментов
        self.layout = QtWidgets.QFormLayout()

        self.layout.addRow(self.start_point_msg)
        self.layout.addRow("X: ", self.start_x_le)
        self.layout.addRow("Y: ", self.start_y_le)

        self.layout.addRow(self.vector_msg)
        self.layout.addRow("Скорость (0-1): ", self.speed_le)
        self.layout.addRow("Направление°: ", self.direction_le)

        self.layout.addRow(self.rotation_msg)
        self.layout.addRow("Макс. ° поворота: ", self.max_angle_of_rotation_le)

        self.layout.addRow(self.vision_msg)
        self.layout.addRow("Угол сектора: ", self.angle_of_vision_le)
        self.layout.addRow("Радиус окружности: ", self.len_of_vision_le)

        self.layout.addRow(self.buttonBox)
        self.setLayout(self.layout)

        # Объявляем атрибуты которые будем получать из модалки
        self.status = None
        self.start_x = None
        self.start_y = None
        self.direction = None
        self.speed = None
        self.max_angle_of_rotation = None
        self.angle_of_vision = None
        self.len_of_vision = None

    # Данная функция отрабатывает при нажатии на кнопку Ок и инициализирует атрибуты, объявленные в конструкторе
    def custom_accept(self):
        self.status = '+'
        self.start_x = float(self.start_x_le.text())
        self.start_y = float(self.start_y_le.text())
        self.direction = float(self.direction_le.text())
        self.speed = float(self.speed_le.text())
        self.max_angle_of_rotation = float(self.max_angle_of_rotation_le.text())
        self.angle_of_vision = float(self.angle_of_vision_le.text())
        self.len_of_vision = float(self.len_of_vision_le.text())
        self.accept()

    # Данная функция отрабатывает при нажатии на кнопку Отмена. Пока она бесполезна, но пусть пока живет (мало ли чо)
    def custom_reject(self):
        self.status = '-'
        self.reject()
